### ISSUE TITLE
大佬，easybox干快点

### ISSUE THREAD

**Issue by Myth1-1** [xianyuyimu/TVBOX-#2]
就美化来说还是挺好的，有以下问题
1,有的源目前版本还闪退，不知道咋回事
2,网盘源可以再加几个吗，比如阿里小站
3,低端，在线之家，注视，这几个都不错
4,动漫源，可以加个异世界动漫吗，omofun目前是客户端，不知道能不能也加入

**Comment by xianyuyimu** [comment]
easybox并不是我所写✍🏻
